
export const DETAILED_DESCRIPTIONS: Record<string, string> = {
  // --- Frontend Development Steps ---
  'fe1': `Internet adalah jaringan global raksasa. Pahami konsep Client-Server: Browser (Client) meminta data, Server mengirimkannya. Pelajari DNS (buku telepon internet) yang menerjemahkan domain ke IP Address. Pahami HTTP/HTTPS sebagai bahasa komunikasi standar dan SSL/TLS untuk enkripsi data.`,
  'fe2': `HTML bukan sekadar menampilkan teks. HTML5 Semantic (menggunakan tag seperti <nav>, <article>, <section>) memberikan makna pada konten. Ini krusial untuk SEO (agar Google paham isi webmu) dan Accessibility (agar screen reader bisa membacakan webmu untuk tunanetra).`,
  'fe3': `CSS mengatur tampilan. Konsep terpenting adalah 'Box Model': setiap elemen HTML adalah kotak yang terdiri dari Margin (jarak luar), Border (garis tepi), Padding (jarak dalam), dan Content. Memahami ini adalah kunci agar layout tidak berantakan.`,
  'fe4': `Lupakan 'float' kuno. Flexbox adalah sistem layout satu dimensi (baris/kolom) yang sangat fleksibel untuk menata komponen. Grid adalah sistem dua dimensi untuk kerangka halaman utama. Kombinasi keduanya membuat Anda bisa meniru layout website apa saja.`,
  'fe5': `Web modern harus 'Responsive'. Gunakan Media Queries (@media) untuk mengubah gaya CSS berdasarkan lebar layar. Terapkan prinsip 'Mobile-First': desain untuk layar kecil dulu (lebih ringan), baru tambahkan kompleksitas untuk layar besar.`,
  'fe6': `JavaScript membuat web 'hidup'. Pelajari tipe data primitif, variabel (let/const), dan logika percabangan (If/Else, Switch). Kuasai Loops (For, While) untuk memproses data berulang. Pahami beda Function Declaration dan Arrow Function.`,
  'fe7': `DOM (Document Object Model) adalah representasi HTML di memori browser. Pelajari cara menyeleksi elemen (querySelector), mengubah isinya, dan merespon interaksi user (Event Listener) seperti klik tombol atau submit form.`,
  'fe8': `Fitur ES6+ membuat koding lebih efisien. Destructuring untuk membongkar objek/array, Template Literals untuk string dinamis, dan Spread Operator. Pelajari Fetch API dan konsep Promise/Async-Await untuk mengambil data dari server tanpa refresh halaman.`,
  'fe9': `Git adalah mesin waktu untuk kodemu. Pelajari: Commit (simpan perubahan), Branch (cabang eksperimen), dan Merge (gabung kode). GitHub adalah tempat kolaborasi. Pahami Pull Request untuk mereview kode sebelum digabungkan ke kode utama.`,
  'fe10': `React mengubah cara pikir dari 'halaman' ke 'komponen'. Pahami JSX, Props (data dari induk ke anak), dan State (data internal yang berubah). Pelajari Lifecycle komponen dengan useEffect. Deploy aplikasimu ke Vercel/Netlify agar bisa diakses dunia.`,
  'fe11': `Prop Drilling (mengoper data melewati banyak lapis komponen) itu merepotkan. Redux atau Zustand menyediakan 'Store' global di mana data bisa diakses komponen mana saja secara langsung. Pahami konsep Immutability dan Reducers.`,
  'fe12': `Tulis kode React yang bersih. Custom Hooks memisahkan logika dari tampilan. Compound Components (seperti <Select> dan <Option>) membuat komponen fleksibel. Pola ini membedakan pemula dan senior.`,
  'fe13': `User benci web lambat. Pelajari Core Web Vitals (LCP, FID, CLS). Gunakan React.lazy dan Suspense untuk memecah kode (Code Splitting) agar browser hanya mendownload yang diperlukan saja. Optimasi gambar dan font.`,
  'fe14': `Jangan biarkan user menemukan bug. Unit Testing (Jest) mengecek fungsi logika. Integration Testing (RTL) mengecek interaksi komponen seolah-olah dilakukan user. TDD (Test Driven Development) adalah mindset menulis test sebelum kode fitur.`,
  'fe15': `Otomatisasi adalah temanmu. CI/CD (Continuous Integration/Deployment) dengan GitHub Actions bisa otomatis menjalankan test setiap kali kamu push kode, dan men-deploy ke server jika semua test lulus.`,

  // --- Backend Development ---
  'be1': `Server jarang punya tampilan grafis (GUI). Kuasai Terminal (CLI). Pelajari perintah dasar Linux (ls, cd, grep, chmod, ssh). Pahami struktur file sistem Linux dan manajemen user/permission dasar.`,
  'be2': `Node.js memungkinkan JavaScript berjalan di server. Pahami arsitektur 'Event-Driven Non-Blocking I/O' yang membuatnya cepat menangani banyak koneksi. Pelajari sistem modul (CommonJS/ESM) dan manajemen paket dengan NPM.`,
  'be3': `Express.js menyederhanakan pembuatan server web. Pelajari Routing (memetakan URL ke fungsi), Middleware (fungsi yang berjalan di tengah request), dan cara menangani HTTP Request (Body, Query, Params) serta mengirim Response.`,
  'be4': `Data harus disimpan permanen. PostgreSQL adalah database relasional (SQL) open-source terkuat. Pahami konsep Tabel, Kolom, Primary Key, Foreign Key, dan Relasi antar tabel (One-to-Many, Many-to-Many).`,
  'be5': `Menulis SQL manual itu rawan salah. ORM seperti Prisma memungkinkan kita berinteraksi dengan database menggunakan kode JavaScript/TypeScript yang aman (Type-safe). Pelajari Schema, Migration, dan Querying via ORM.`,
  'be6': `API adalah jembatan komunikasi. Desain RESTful API yang baik menggunakan HTTP Verbs (GET, POST, PUT, DELETE) dan Status Codes (200, 400, 500) yang tepat. Pahami struktur endpoint yang bersih dan konsisten.`,
  'be7': `Jangan simpan password plain text! Gunakan Hashing (bcrypt). Pelajari JWT (JSON Web Token) untuk autentikasi stateless: user login sekali, dapat token, dan token dipakai untuk akses berikutnya.`,
  'be8': `Jangan pernah percaya input user. Validasi data masuk menggunakan library seperti Zod atau Joi untuk mencegah data sampah atau berbahaya masuk ke sistem. Berikan pesan error yang jelas ke frontend.`,
  'be9': `Test logika backendmu. Gunakan Jest dan Supertest untuk mensimulasikan request ke API endpoint dan memastikan response-nya benar (status code, struktur data JSON) tanpa membuka Postman manual.`,
  'be10': `Aplikasi harus bisa jalan di mana saja. Docker membungkus aplikasi dan dependensinya ke dalam 'Container'. Pelajari Dockerfile dan Docker Compose. Deploy container ini ke layanan cloud modern.`,

  // --- DevOps Basics ---
  'do1': `DevOps bukan sekadar tools, tapi budaya kolaborasi antara Developer (pembuat) dan Operations (pengelola). Pahami model CAMS: Culture, Automation, Measurement, Sharing. Tujuannya: rilis software lebih cepat dan aman.`,
  'do2': `Dalami Linux lebih lanjut. Shell Scripting (Bash) memungkinkanmu membuat program otomatisasi sederhana. Pahami manajemen proses (systemd), networking dasar (ports, firewall), dan permission file tingkat lanjut.`,
  'do3': `Docker memecahkan masalah "It works on my machine". Image adalah cetakan, Container adalah kue-nya. Pelajari cara membuat Dockerfile efisien (multi-stage build) untuk aplikasi NodeJS atau Python.`,
  'do4': `Aplikasi nyata butuh database, cache, dll. Docker Compose memungkinkanmu mendefinisikan dan menjalankan multi-container application dengan satu file YAML. Sangat berguna untuk lingkungan development lokal.`,
  'do5': `CI (Continuous Integration): Menggabungkan kode ke main branch sesering mungkin dengan test otomatis. CD (Continuous Deployment): Rilis otomatis ke produksi. Ini menghilangkan "Integration Hell" di akhir proyek.`,
  'do6': `GitHub Actions adalah platform CI/CD gratis yang terintegrasi. Pelajari syntax YAML workflow: Triggers (on push), Jobs, dan Steps. Buat pipeline yang otomatis menjalankan linter dan test saat Pull Request.`,
  'do7': `Infrastructure as Code (IaC) berarti mengelola server dengan kode, bukan klik-klik manual. Terraform adalah standar industri. Pelajari cara mendefinisikan resource cloud (AWS/GCP) secara deklaratif.`,
  'do8': `Kamu tidak bisa memperbaiki apa yang tidak kamu ukur. Monitoring memberi visibilitas kesehatan sistem (CPU, RAM). Logging mencatat apa yang terjadi. Pelajari dasar Prometheus (metrics) dan Grafana (dashboard).`,

  // --- AWS Cloud ---
  'aws1': `Cloud Computing adalah menyewa komputer orang lain (Amazon) lewat internet. On-premise: beli server sendiri (Capex). Cloud: bayar sewa per jam (Opex). Pahami model IaaS, PaaS, dan SaaS.`,
  'aws2': `AWS punya data center di seluruh dunia. Region adalah lokasi fisik (misal: Singapore). Availability Zone (AZ) adalah data center terpisah di dalam Region. Selalu desain sistem yang tahan jika satu AZ mati.`,
  'aws3': `IAM (Identity & Access Management) adalah satpam AWS. Jangan pakai akun root! Buat User dengan hak akses minimal (Least Privilege). Pahami Groups, Roles (untuk layanan), dan Policies (dokumen izin JSON).`,
  'aws4': `EC2 (Elastic Compute Cloud) adalah komputer virtual. Pilih tipe instance sesuai kebutuhan (T3 untuk umum, C5 untuk komputasi berat). Pelajari Security Groups (firewall virtual) untuk membuka port HTTP/SSH.`,
  'aws5': `S3 (Simple Storage Service) adalah penyimpanan objek (file) yang sangat murah dan awet. Pahami konsep Bucket, Object Key, dan Storage Classes (Standard vs Glacier untuk arsip). Bisa dipakai hosting web statis.`,
  'aws6': `VPC (Virtual Private Cloud) adalah jaringan pribadi virtualmu di AWS. Kamu mengatur IP range, Subnet (Public/Private), Route Table, dan Internet Gateway. Ini fondasi isolasi keamanan jaringan cloud.`,
  'aws7': `RDS (Relational Database Service) memudahkan setup database. AWS yang mengurus backup, patch OS, dan scaling. Kamu tinggal pakai. Mendukung MySQL, PostgreSQL, dll. Pahami konsep Read Replicas untuk performa.`,
  'aws8': `Lambda adalah layanan Serverless. Kamu upload kode, AWS menjalankannya hanya saat dipicu (misal: ada upload foto ke S3). Kamu bayar per milidetik durasi kode jalan. Tidak perlu pusing manajemen server.`,
  'aws9': `Cloud bisa mahal jika tidak hati-hati. Gunakan AWS Cost Explorer untuk melihat tren biaya. Pasang AWS Budgets agar dapat email notifikasi jika tagihan menyentuh batas tertentu (misal $10).`,
  'aws10': `Sertifikasi AWS Cloud Practitioner memvalidasi pemahaman dasarmu. Fokus pada konsep cloud, keamanan dasar, layanan inti, dan model harga. Ini nilai tambah besar di CV IT.`,

  // --- Cyber Security ---
  'cs1': `Pahami bagaimana data bergerak. TCP/IP, OSI Model (Layer 1-7), IP Address, Subnetting, dan Common Ports (80, 443, 22). Anda tidak bisa mengamankan jaringan yang tidak Anda pahami cara kerjanya.`,
  'cs2': `Kali Linux adalah OS standar hacker & pentester. Biasakan diri dengan terminal Linux. Pelajari command line tools bawaan untuk manipulasi file, networking, dan scripting dasar.`,
  'cs3': `OSINT (Open Source Intelligence) adalah tahap pengumpulan informasi (Reconnaissance) dari sumber publik. Gunakan Google Dorks, Shodan, dan Whois untuk memetakan target tanpa menyentuh sistem mereka secara langsung.`,
  'cs4': `Nmap adalah "mata" seorang pentester. Pelajari cara scan IP untuk menemukan port terbuka, layanan yang berjalan, dan versi OS. Informasi ini krusial untuk mencari celah keamanan (exploit) yang spesifik.`,
  'cs5': `OWASP Top 10 adalah daftar 10 risiko keamanan web terbesar. Pelajari konsepnya: Broken Access Control, Cryptographic Failures, Injection, dll. Ini adalah "kitab suci" keamanan web.`,
  'cs6': `SQL Injection terjadi saat input user memanipulasi query database. XSS (Cross-Site Scripting) terjadi saat script jahat disisipkan ke web korban. Pelajari cara kerja dan cara mencegahnya (sanitasi input).`,
  'cs7': `Kriptografi menjaga kerahasiaan. Bedakan Enkripsi Simetris (satu kunci) vs Asimetris (public/private key). Pahami Hashing (satu arah) untuk password. Jangan pernah membuat algoritma enkripsi sendiri!`,
  'cs8': `Metasploit adalah framework untuk mengembangkan dan menjalankan exploit. Pelajari cara mencari modul exploit untuk kerentanan tertentu, men-set payload (misal: reverse shell), dan mendapatkan akses ke target.`,
  'cs9': `Setelah masuk sistem (foothold), tujuannya adalah menjadi admin/root. Privilege Escalation melibatkan mencari miskonfigurasi, kernel exploit, atau password tersimpan yang bisa dimanfaatkan untuk naik level hak akses.`,
  'cs10': `Skill terpenting: Komunikasi. Hacker etis harus bisa menulis laporan yang menjelaskan temuan, dampaknya bagi bisnis, dan langkah perbaikan (remediasi) dengan bahasa yang dipahami manajemen.`,

  // --- Python Data Science ---
  'pds1': `Python ramah pemula tapi powerful. Mulai dengan instalasi Anaconda/Miniconda. Pahami indentasi (spasi) sebagai struktur kode. Pelajari variabel, tipe data (int, float, string, bool), dan operator matematika dasar.`,
  'pds2': `Kuasai struktur data bawaan. List (urutan data bisa diubah), Tuple (urutan data permanen), Dictionary (key-value pair untuk data kompleks), dan Set (kumpulan data unik). Pahami indexing dan slicing.`,
  'pds3': `Logika program ada di Control Flow: If-Elif-Else. Automasi tugas dengan Loops (For/While). Bungkus kode berulang dalam Function agar modular dan rapi. Pahami scope variabel (lokal vs global).`,
  'pds4': `NumPy (Numerical Python) adalah fondasi komputasi ilmiah. Array NumPy jauh lebih cepat dan hemat memori dibanding List Python biasa. Pelajari operasi vektorisasi (matematika tanpa loop) dan broadcasting.`,
  'pds5': `Pandas adalah tool utama Data Analyst. DataFrame mirip Excel tapi diprogram. Pelajari cara load data (read_csv), inspeksi data (head, info), filtering, sorting, grouping, dan merging datasets.`,
  'pds6': `Data asli pasti kotor. Data Cleaning meliputi: menangani Missing Values (isi rata-rata atau hapus?), menghapus duplikat, memperbaiki format tipe data, dan menangani Outliers (data aneh) yang bisa merusak analisis.`,
  'pds7': `Visualisasi membuat pola terlihat. Matplotlib adalah library dasar (low-level). Seaborn dibangun di atasnya (high-level) untuk grafik statistik yang cantik. Pahami kapan pakai Bar, Line, Scatter, atau Histogram.`,
  'pds8': `EDA (Exploratory Data Analysis) adalah proses "berkenalan" dengan data. Gunakan statistik deskriptif (Mean, Median, Std Dev) dan visualisasi untuk mencari pola, korelasi, dan anomali sebelum membuat model.`,
  'pds9': `Scikit-Learn adalah library ML standar. Mulai dengan Supervised Learning sederhana: Linear Regression (prediksi angka) dan Logistic Regression (klasifikasi ya/tidak). Pahami konsep Train-Test Split.`,
  'pds10': `Jupyter Notebook adalah kanvas kerjamu. Gabungkan kode, output, grafik, dan narasi teks (Markdown) dalam satu dokumen. Proyek akhirmu harus bercerita: Masalah -> Data -> Analisis -> Kesimpulan.`,

  // --- Mobile App Dev ---
  'md1': `React Native (RN) memungkinkan bikin aplikasi iOS & Android pakai JavaScript. Expo adalah toolchain yang memudahkan setup tanpa instal Android Studio/Xcode yang berat di awal. Fitur 'Hot Reload' mempercepat development.`,
  'md2': `RN tidak pakai HTML. Ganti <div> dengan <View>, <p> dengan <Text>, <img> dengan <Image>. Pahami bahwa komponen ini akan dirender menjadi native UI widget asli HP, bukan sekadar webview.`,
  'md3': `Layouting di RN pakai Flexbox, mirip CSS tapi default-nya vertikal (column). Tidak ada CSS Class global, kita pakai StyleSheet object. Pahami konsep styling responsif agar tampilan pas di berbagai ukuran layar HP.`,
  'md4': `Aplikasi jarang cuma satu layar. React Navigation adalah standar industri. Stack Navigator untuk navigasi tumpuk (ada tombol back). Tab Navigator untuk menu bawah. Pelajari cara kirim data (params) antar layar.`,
  'md5': `Menampilkan list data panjang (seperti chat/feed) bisa berat. Jangan pakai ScrollView dan map! Gunakan FlatList yang hanya me-render item yang terlihat di layar (lazy loading) untuk performa 60fps.`,
  'md6': `Interaksi user via TextInput. Pelajari cara handle state input, keyboard type (numeric, email), dan event onChangeText. Buat form yang user-friendly dengan validasi real-time.`,
  'md7': `Aplikasi butuh data internet. Gunakan Fetch API atau Axios untuk request ke Backend. Pahami handling state: Loading (spinner), Success (tampil data), dan Error (tampil pesan gagal).`,
  'md8': `Kekuatan HP ada di hardwarenya. Expo SDK menyediakan akses mudah ke Kamera, Lokasi (GPS), Galeri Foto, Sensor, dan Notifikasi. Pelajari cara minta izin (Permissions) ke user.`,
  'md9': `Saat aplikasi kompleks, prop drilling jadi masalah. Gunakan Context API untuk data sederhana (Theme, Auth) atau library seperti Zustand/Redux untuk manajemen state global yang lebih terstruktur.`,
  'md10': `Saatnya rilis! EAS Build (Expo Application Services) bisa mem-build file .apk (Android) dan .ipa (iOS) di cloud tanpa butuh Mac mahal. Pelajari proses submit ke Google Play Console dan App Store Connect.`,

  // --- AI Engineering ---
  'ai1': `LLM (Large Language Model) bekerja dengan memprediksi kata (token) berikutnya berdasarkan probabilitas statistik. Pahami Tokenization, Context Window, dan konsep dasar Transformer architecture.`,
  'ai2': `Prompt Engineering adalah seni 'memprogram' AI dengan bahasa manusia. Teknik: Zero-shot (langsung tanya), Few-shot (beri contoh), Chain-of-Thought (minta AI berpikir step-by-step) meningkatkan akurasi drastis.`,
  'ai3': `Integrasi via API. Dapatkan API Key (OpenAI/Gemini). Pelajari parameter: Model (GPT-4 vs 3.5), Temperature (Kreativitas vs Determinisme), Max Tokens. Buat script Python sederhana untuk memanggil model.`,
  'ai4': `Komputer tidak paham kata, tapi paham angka. Embeddings mengubah teks menjadi vektor angka. Kalimat dengan makna mirip akan memiliki vektor yang 'dekat'. Ini dasar Semantic Search.`,
  'ai5': `LLM pengetahuannya terbatas waktu training. RAG (Retrieval Augmented Generation) memungkinkan AI menjawab berdasarkan data pribadimu (PDF/Docs) dengan cara mencari info relevan dulu lalu disuapkan ke prompt.`,
  'ai6': `LangChain adalah framework untuk merangkai komponen AI. Membuat aplikasi yang butuh memori percakapan, akses dokumen, dan format output terstruktur jauh lebih mudah dengan abstraksi LangChain.`,
  'ai7': `Prompting mentok? Fine-Tuning melatih ulang sebagian kecil model dengan dataset khususmu agar model mengerti gaya bahasa atau format spesifik domain (misal: hukum/medis) dengan lebih baik.`,
  'ai8': `Level tertinggi: AI Agents. AI yang diberi akses ke 'Tools' (Google Search, Calculator, Database). AI bisa merencanakan langkah: "Saya perlu cari info X, lalu hitung Y, baru jawab user".`,

  // --- Digital Marketing ---
  'dm1': `Marketing bukan sekadar jualan. Pahami Funnel AIDA: Awareness (Tahu), Interest (Tertarik), Desire (Ingin), Action (Beli). Setiap tahap butuh pendekatan konten beda.`,
  'dm2': `Copywriting adalah salesmanship dalam tulisan. Headline adalah 80% kesuksesan. Gunakan formula PAS (Problem-Agitation-Solution) atau AIDA dalam caption dan landing page. Fokus pada Manfaat (Benefit), bukan Fitur.`,
  'dm3': `SEO (Search Engine Optimization) mendatangkan trafik gratis jangka panjang. Riset Keyword: apa yang dicari orang? On-Page: Judul, Meta, Konten berkualitas. Off-Page: Backlink dari web lain.`,
  'dm4': `Sosmed butuh strategi. Tentukan Content Pillars (edukasi, hiburan, promosi). Buat Content Calendar agar konsisten. Pahami karakteristik unik tiap platform (IG Visual, TikTok Video, LinkedIn Pro).`,
  'dm5': `Iklan berbayar (Ads) mempercepat hasil. Meta Ads menargetkan minat/perilaku. Google Search Ads menargetkan intensi (kata kunci). Pahami metrik: CPC, CTR, ROAS. Mulai dengan budget kecil untuk tes.`,
  'dm6': `Email marketing punya ROI tertinggi. Jangan beli database! Kumpulkan Leads (email) dengan Lead Magnet (ebook/webinar gratis). Kirim newsletter bernilai, bukan spam jualan terus.`,
  'dm7': `Content Marketing adalah memberi nilai dulu, jualan kemudian. Edukasi pasar tentang masalah mereka. Saat mereka siap beli, brand kamulah Top of Mind mereka.`,
  'dm8': `Data tidak bohong. Google Analytics melacak siapa pengunjungmu, dari mana asalnya, dan apa yang mereka lakukan. Fokus pada metrik yang berdampak pada bisnis (Konversi), bukan Vanity Metrics (Likes).`,
  'dm9': `CRO (Conversion Rate Optimization). Mendatangkan trafik itu mahal, memaksimalkan yang datang itu cerdas. A/B Testing warna tombol, judul, atau posisi form bisa menaikkan penjualan tanpa tambah budget iklan.`,
  'dm10': `Dokumentasikan hasil kerjamu. Portofolio marketer bukan gambar cantik, tapi data: "Berhasil menaikkan trafik 50% dalam 3 bulan" atau "Menghasilkan omzet 100jt dengan budget iklan 10jt".`,

  // --- Freelancing ---
  'fl1': `Jangan jadi "Palu Gada" (Apa Lu Mau Gue Ada). Spesialis dibayar lebih mahal. Tentukan Niche spesifik: "Web Desainer untuk UMKM Kuliner" lebih menjual daripada sekadar "Web Desainer".`,
  'fl2': `Portofolio harus berupa Studi Kasus. Jangan cuma tempel gambar hasil. Jelaskan: Masalah Klien -> Solusi Kamu -> Hasil/Dampak bagi bisnis klien. Ini membangun kepercayaan.`,
  'fl3': `Strategi Harga: Hindari perang harga murah. Pahami Hourly Rate vs Fixed Price vs Value-Based Pricing. Tujuannya adalah dibayar berdasarkan nilai yang kamu berikan, bukan sekadar waktu kerjamu.`,
  'fl4': `LinkedIn adalah tambang emas klien B2B. Optimasi profil: Headline yang jelas (I help X achieve Y), Foto profesional, dan Featured section berisi portofolio terbaik.`,
  'fl5': `Jangan tunggu bola. Lakukan Cold Outreach. Kirim pesan personal ke target klien potensial. Tawarkan solusi untuk masalah yang mungkin mereka hadapi, jangan langsung jualan hard selling.`,
  'fl6': `Proposal yang memenangkan hati klien fokus pada MEREKA, bukan kamu. Ulangi masalah mereka, tawarkan solusi step-by-step, timeline jelas, dan investasi (harga) yang transparan.`,
  'fl7': `Kontrak kerja melindungi kedua pihak. Atur ruang lingkup kerja (Scope), revisi (jumlah & batas), hak cipta, dan termin pembayaran. Jangan mulai kerja tanpa kontrak atau DP.`,
  'fl8': `Manajemen Klien: Komunikasi adalah kunci. Update progres berkala. Edukasi klien jika permintaannya di luar scope. Jadilah partner strategis, bukan sekadar tukang suruh.`,
  'fl9': `Waktu adalah uang. Pisahkan waktu 'Deep Work' (mengerjakan proyek) dan waktu 'Admin' (balas email, cari klien). Gunakan teknik Time Blocking agar tidak burnout.`,
  'fl10': `Pisahkan rekening pribadi dan bisnis. Catat pemasukan & pengeluaran. Siapkan dana pajak dan asuransi mandiri. Freelancer adalah CEO bagi dirinya sendiri.`,

  // --- Personal Finance ---
  'pf1': `Audit finansial: Sadari posisimu. Hitung Net Worth (Aset - Utang). Catat Cashflow (Pemasukan vs Pengeluaran) bulan lalu. Kamu tidak bisa memperbaiki apa yang tidak kamu ukur.`,
  'pf2': `Budgeting bukan membatasi, tapi mengarahkan uang. Metode 50/30/20: 50% Kebutuhan (Wajib), 30% Keinginan (Hiburan), 20% Tabungan/Investasi/Utang. Sesuaikan dengan realita.`,
  'pf3': `Dana Darurat adalah bantalan hidup. Kumpulkan 3-6 bulan pengeluaran pokok di rekening terpisah yang mudah dicairkan tapi tidak diotak-atik. Ini mencegahmu berutang saat musibah.`,
  'pf4': `Utang Konsumtif (bunga tinggi) adalah musuh. Metode Snowball: Lunasi utang terkecil dulu (motivasi psikologis). Metode Avalanche: Lunasi bunga terbesar dulu (hemat uang). Pilih yang cocok.`,
  'pf5': `Inflasi memakan tabungan. Investasi tujuannya melawan inflasi. Pahami Risk vs Return: High Risk High Return. Kenali profil risikomu: Konservatif, Moderat, atau Agresif?`,
  'pf6': `Saham adalah bukti kepemilikan perusahaan. Beli saham = beli bisnis. Pelajari Analisis Fundamental (Kesehatan perusahaan) vs Teknikal (Grafik harga). Untuk pemula, investasi jangka panjang lebih aman.`,
  'pf7': `Reksa Dana / ETF adalah keranjang investasi yang dikelola manajer. Cocok untuk pemula karena diversifikasi otomatis dan modal kecil. Ada Pasar Uang (Aman), Obligasi (Menengah), Saham (Agresif).`,
  'pf8': `Pensiun terasa jauh, tapi butuh biaya besar karena Compound Interest butuh waktu. Semakin dini mulai, semakin ringan. Manfaatkan DPLK atau instrumen jangka panjang lainnya.`,

  // --- Product Management ---
  'pmt1': `Product Manager (PM) adalah "CEO mini" produk. Tugasmu bukan koding atau desain, tapi memastikan tim membangun produk yang TEPAT (bernilai bisnis & user butuh) dengan layak & bisa dibuat.`,
  'pmt2': `Jangan tebak-tebakan. User Research (Interview, Survey) memvalidasi asumsi. Bedakan apa yang user 'katakan' mereka mau vs apa yang sebenarnya mereka 'lakukan/butuhkan' (Pain Points).`,
  'pmt3': `Lihat kompetitor. Analisis SWOT (Strengths, Weaknesses, Opportunities, Threats). Cari celah pasar yang belum terlayani atau bisa dilayani lebih baik oleh produkmu.`,
  'pmt4': `MVP (Minimum Viable Product) bukan produk jelek, tapi produk dengan fitur minimal yang cukup untuk belajar dari pasar. Rilis cepat, dapatkan feedback, iterasi. Jangan buat "sempurna" di awal.`,
  'pmt5': `PRD (Product Requirement Document) adalah panduan tim. Harus jelas: Masalah apa yang dipecahkan? Siapa usernya? Fitur apa saja? Bagaimana flow-nya? Kriteria suksesnya apa?`,
  'pmt6': `Ide fitur pasti banyak, resource terbatas. Prioritas adalah kunci. Framework RICE (Reach, Impact, Confidence, Effort) atau MoSCoW (Must have, Should have, Could have) membantu memilih fitur objektif.`,
  'pmt7': `Ukur kesuksesan dengan Data. Tentukan North Star Metric (satu metrik utama). Pantau Acquisition, Activation, Retention, Referral, Revenue (Pirate Metrics AARRR).`,
  'pmt8': `Go-to-Market Strategy. Produk bagus kalau tidak ada yang tahu akan gagal. Rencanakan peluncuran: Marketing, Training CS, FAQ, dan komunikasi ke user.`,

  // --- Startup Founder ---
  'st1': `Ide startup terbaik datang dari masalah yang kamu alami sendiri. Validasi masalahnya dulu: Apakah ini masalah 'sakit gigi' (harus segera diobati) atau 'vitamin' (bagus tapi ga mendesak)?`,
  'st2': `Validasi pasar sebelum bikin produk. The Mom Test: Jangan tanya "Ideku bagus ga?" (orang akan bohong sopan). Tanya tentang perilaku masa lalu mereka terkait masalah tersebut. Coba jual sebelum barang ada (Pre-order).`,
  'st3': `Business Model Canvas (BMC) memetakan strategi dalam 1 halaman: Value Prop, Customer Segments, Revenue Streams, Cost Structure, Channels, dll. Jauh lebih efektif dari Business Plan tebal.`,
  'st4': `Lean Startup Methodology: Build-Measure-Learn. Buat hipotesis, jalankan eksperimen termurah untuk mengujinya, ukur data, pelajari, lalu Pivot (ubah arah) atau Persevere (lanjut).`,
  'st5': `Sendirian itu berat. Co-founder ideal melengkapi skillmu (misal: satu jago Bisnis/Sales, satu jago Teknis/Product). Kesamaan visi & nilai (values) lebih penting dari skill.`,
  'st6': `Pitch Deck adalah cerita bisnismu untuk investor. Struktur standar: Masalah, Solusi, Market Size (TAM/SAM/SOM), Model Bisnis, Traksi, Tim, dan Ask (butuh dana berapa).`,
  'st7': `Fundraising: Bootstrapping (uang sendiri/hasil jualan) memberikan kontrol penuh. Venture Capital (VC) memberi dana besar & akses tapi ambil saham & menuntut pertumbuhan cepat. Pilih sesuai tujuanmu.`,
  'st8': `Legalitas & HAKI penting. Founder Agreement (pembagian saham & vesting) mencegah ribut di masa depan. Daftarkan merek dagang. Pahami kewajiban pajak badan.`,

  // --- Project Management Agile ---
  'pm1': `Project Management adalah seni menyelesaikan sesuatu. Pahami siklus hidup: Inisiasi (Start), Perencanaan (Plan), Eksekusi (Do), Pemantauan (Check), Penutupan (Close).`,
  'pm2': `Waterfall (tradisional) itu linear, cocok untuk konstruksi. Agile (iteratif) cocok untuk software karena kebutuhan bisa berubah. Agile fokus pada kolaborasi dan software yang bekerja, bukan dokumentasi tebal.`,
  'pm3': `Scrum adalah framework Agile populer. Ada Roles (PO, Scrum Master, Team), Events (Sprint, Daily Standup, Review, Retro), dan Artifacts (Backlog, Increment). Kerja dibagi dalam siklus pendek (Sprint).`,
  'pm4': `Kanban fokus pada visualisasi alur kerja (To Do, In Progress, Done) dan membatasi WIP (Work In Progress). Tujuannya aliran kerja yang lancar dan identifikasi bottleneck (macet) dengan cepat.`,
  'pm5': `Scope Creep (fitur nambah terus) membunuh proyek. Dokumen Scope yang jelas dan Change Management Process membantu menjaga proyek tetap on-track dan on-budget.`,
  'pm6': `Manajemen Risiko: Identifikasi apa yang mungkin salah (Risk), seberapa besar dampaknya, dan siapkan rencana mitigasi (Plan B). Lebih baik sedia payung sebelum hujan.`,
  'pm7': `Stakeholder Management. Siapa yang punya kepentingan? (Bos, Klien, Tim). Pahami ekspektasi mereka. Komunikasi yang buruk adalah penyebab utama kegagalan proyek.`,
  'pm8': `Sprint Planning: Tim memilih item dari Product Backlog untuk dikerjakan dalam satu Sprint (biasanya 2 minggu). Estimasi beban kerja realistis agar tim tidak burnout.`,
  'pm9': `Retrospective adalah jantung Agile. Di akhir sprint, tim berkumpul membahas: Apa yang berjalan baik? Apa yang kurang? Apa yang harus diperbaiki di sprint depan? Continuous Improvement.`,
  'pm10': `Kuasai Tools. Jira, Trello, atau Asana bukan sekadar to-do list. Pelajari fitur advanced: Dependencies, Gantt Chart, Reporting, dan Automations untuk efisiensi tim.`,

  // --- Sales Mastery ---
  'sl1': `Sales bukan memaksa orang beli, tapi membantu orang memecahkan masalah dengan solusimu. Ubah mindset dari "Jualan" menjadi "Melayani". Orang suka beli, tapi benci dijualin.`,
  'sl2': `Product Knowledge mutlak. Tapi jangan cuma hafal Fitur (spek teknis), terjemahkan jadi Manfaat (apa gunanya buat user?). Contoh: "RAM 8GB" (Fitur) -> "Bisa buka banyak aplikasi tanpa lemot" (Manfaat).`,
  'sl3': `Prospecting: Mencari calon pembeli ideal (Leads). Jangan tembak sembarang burung. Tentukan Ideal Customer Profile (ICP). Kualitas lead lebih penting dari kuantitas.`,
  'sl4': `Elevator Pitch: Bisa jelaskan tawaranmu dalam 30-60 detik? Rumus: Siapa kamu + Apa yang kamu tawarkan + Untuk siapa + Apa manfaat utamanya. Harus jelas dan memikat.`,
  'sl5': `Active Listening. Penjual hebat mendengarkan 80%, bicara 20%. Gali kebutuhan klien dengan pertanyaan terbuka (SPIN Selling). Biarkan klien menyadari sendiri bahwa mereka butuh solusimu.`,
  'sl6': `Handling Objections (Penolakan). "Harganya mahal", "Nanti dulu". Jangan defensif. Validasi perasaan mereka ("Saya paham budget isu penting"), lalu isolasi keberatan dan beri perspektif baru/nilai tambah.`,
  'sl7': `Negosiasi tujuannya Win-Win. Jangan langsung diskon harga. Tawarkan value lain (bonus, termin pembayaran, support lebih). Ketahui BATNA (alternatif terbaikmu jika deal gagal) agar percaya diri.`,
  'sl8': `Closing adalah meminta keputusan. Jangan gantung. Teknik: Option Close ("Mau paket A atau B?"), Urgency ("Promo berakhir besok"), atau Assumptive ("Kapan mau dikirim?").`,
  'sl9': `Follow Up adalah tempat uang berada. Kebanyakan sales menyerah setelah 1x kontak. Statistik butuh 5-8x kontak untuk deal. Lakukan follow up yang memberi nilai, bukan sekadar "Jadi beli gak?".`,
  'sl10': `CRM (Customer Relationship Management) system. Jangan andalkan ingatan. Catat detail prospek, riwayat interaksi, dan status deal di pipeline. Data rapi = Sales rapi.`,

  // --- Content Creation Shortform ---
  'cc1': `Pahami "Bahasa" tiap platform. TikTok/Reels suka konten raw, autentik, cepat, dan menghibur. YouTube Shorts bisa sedikit lebih terpoles. Algoritma memprioritaskan Watch Time & Retention.`,
  'cc2': `Hook (3 detik pertama) adalah segalanya. Jika hook gagal, video di-scroll. Gunakan visual aneh, pertanyaan provokatif, atau pernyataan kontroversial ("Stop lakukan ini!").`,
  'cc3': `Scripting video pendek: Hook -> Masalah/Relate -> Solusi/Isi -> Call to Action (CTA). Jaga kalimat tetap padat. Hapus bagian "hallo guys" yang bertele-tele.`,
  'cc4': `Kualitas Audio > Video. Orang mau nonton video buram, tapi langsung skip audio kresek/kecil. Gunakan mic eksternal murah atau rekam di tempat sepi. Cahaya matahari jendela adalah lighting terbaik gratis.`,
  'cc5': `Editing di CapCut. Jump cut (potong jeda diam) biar dinamis. Gunakan B-Roll (gambar tempelan) untuk visualisasi cerita. Zoom in/out halus untuk menjaga perhatian mata penonton.`,
  'cc6': `Text Overlay & Caption. Banyak orang nonton tanpa suara. Tambahkan teks inti di layar. Caption otomatis membantu aksesibilitas dan retensi penonton.`,
  'cc7': `Trending Audio bisa mendongkrak views, tapi harus relevan. Gunakan sound viral dengan twist/niche kamu sendiri. Jangan asal pakai lagu joget untuk konten serius.`,
  'cc8': `Branding Visual. Konsistensi font, warna, dan tone bicara membuatmu mudah dikenali. Profil bio harus jelas: Siapa kamu & Apa yang penonton dapatkan.`,
  'cc9': `Analisis Data. Cek Retention Graph. Di detik berapa orang drop? Itu berarti bagian itu membosankan. Perbaiki di video berikutnya. Belajar dari performa konten sendiri.`,
  'cc10': `Monetisasi creator. Jangan cuma andalkan views. Bangun kolam sendiri (email list/komunitas). Jual jasa, produk digital, atau affiliate yang relevan dengan audiensmu.`,

  // --- UX Design Path ---
  'ux1': `UX bukan UI. UX (User Experience) fokus pada RASA dan KEMUDAHAN penggunaan. Riset adalah fondasi. Jangan mendesain berdasarkan asumsi ("Saya suka ini"), tapi data ("User butuh ini").`,
  'ux2': `User Persona adalah karakter fiksi mewakili target user. "Budi, 25th, sibuk, butuh cepat". Saat desain, tanya: "Apakah ini membantu Budi?". Empathy Map membantu memahami apa yang user rasa/pikir/lakukan.`,
  'ux3': `Information Architecture (IA). Bagaimana struktur konten diorganisir? User harus mudah menemukan menu. Teknik Card Sorting membantu memahami cara user mengelompokkan informasi.`,
  'ux4': `User Flow menggambarkan langkah user dari A ke B (misal: Buka App -> Cari Barang -> Checkout). Pastikan flow efisien dan minim hambatan (friction).`,
  'ux5': `Wireframing adalah kerangka kasar (low-fidelity). Fokus pada tata letak elemen, bukan warna/font. Sketsa di kertas atau whiteboard jauh lebih cepat untuk eksplorasi ide awal.`,
  'ux6': `Figma adalah standar industri saat ini. Pelajari Frame, Auto Layout (wajib!), Components, dan Variants. Fitur kolaborasi real-time memudahkan kerja tim.`,
  'ux7': `UI Principles: Visual Hierarchy (mana yang penting harus menonjol), Konsistensi, White Space (ruang napas), dan Kontras warna. Desain cantik tapi membingungkan = UX buruk.`,
  'ux8': `Prototyping membuat desain statis menjadi interaktif (bisa diklik). Ini simulasi produk akhir untuk dites. Pahami transisi dan animasi mikro untuk pengalaman lebih halus.`,
  'ux9': `Usability Testing. Minta orang (bukan tim sendiri) mencoba prototype. Amati di mana mereka bingung/macet. Jangan arahkan mereka. Feedback user asli adalah validasi terbaik.`,
  'ux10': `Studi Kasus UX adalah portofolio utamamu. Ceritakan proses: Masalah -> Riset -> Ide -> Desain -> Test -> Revisi -> Hasil. Perekrut ingin lihat pola pikir pemecahan masalahmu.`,

  // --- Graphic Design ---
  'gd1': `Prinsip Desain: Balance (Keseimbangan), Contrast (Pembeda), Emphasis (Fokus), Repetition (Konsistensi), dan White Space. Ini aturan main agar desain enak dilihat dan efektif.`,
  'gd2': `Teori Warna. Pahami Roda Warna (Complementary, Analogous). Warna punya psikologi: Merah (Berani/Lapar), Biru (Trust/Tenang). Pilih palet warna yang sesuai mood brand.`,
  'gd3': `Tipografi. Serif (klasik/formal) vs Sans Serif (modern/bersih). Batasi maksimal 2-3 jenis font. Perhatikan Kerning (jarak antar huruf) dan Leading (jarak antar baris) agar mudah dibaca.`,
  'gd4': `Grid System & Layout. Grid membantu menata elemen agar rapi dan terstruktur. Rule of Thirds membantu komposisi yang dinamis. Jangan takut ruang kosong (negative space).`,
  'gd5': `Canva adalah tool gateway yang powerful. Pahami cara pakai template tapi dimodifikasi agar unik. Pelajari fitur Magic Resize dan Brand Kit untuk efisiensi konten sosmed.`,
  'gd6': `Logo Design. Logo harus Simple, Memorable, Timeless, Versatile (bagus di hitam putih/ukuran kecil), dan Appropriate (sesuai industri). Hindari tren sesaat.`,
  'gd7': `Vector (Illustrator/Corel) vs Raster (Photoshop). Vector berbasis matematika, bisa diperbesar tanpa pecah (untuk logo). Raster berbasis piksel (untuk foto). Jangan buat logo pakai Photoshop!`,
  'gd8': `Brand Identity lebih dari logo. Ini mencakup warna, font, pola, gaya foto, dan tone of voice. Brand Guideline memastikan konsistensi visual di semua media.`,
  'gd9': `Visual Hierarchy mengarahkan mata audiens. Elemen terpenting harus paling menonjol (lewat ukuran, warna, atau posisi). User harus tahu harus baca apa duluan.`,
  'gd10': `Siap Cetak vs Digital. Digital pakai RGB & 72 PPI. Cetak pakai CMYK & 300 DPI. Pahami Bleed (lebihkan pinggiran) agar hasil potong rapi. Kesalahan mode warna bisa bikin hasil cetak kusam.`,

  // --- Video Editing Pro ---
  've1': `Organisasi file adalah separuh pekerjaan. Folder structure yang rapi (Footage, Audio, Project Files, Exports) mencegah pusing saat proyek membesar. Biasakan proxy workflow untuk footage berat.`,
  've2': `Editing Cuts. J-Cut (audio masuk dulu sebelum video) dan L-Cut (video ganti tapi audio lanjut) membuat dialog mengalir natural. Jump Cut untuk mempercepat tempo. Match Cut untuk transisi artistik.`,
  've3': `Pacing & Rhythm. Edit berdasarkan ketukan musik atau emosi cerita. Video cepat memberi energi, video lambat memberi dramatisasi. Jangan biarkan durasi shot membosankan.`,
  've4': `Color Correction: Memperbaiki masalah (exposure, white balance) agar gambar terlihat normal dan konsisten antar klip. Wajib dilakukan sebelum Grading. Scope (Waveform/Vectorscope) lebih jujur dari mata.`,
  've5': `Color Grading: Memberi 'Look' atau mood artistik (misal: Teal & Orange, Cinematic, Sepia). Gunakan LUTs sebagai basis tapi sesuaikan lagi opacity-nya.`,
  've6': `Sound Design (SFX) menghidupkan video. Tambahkan ambience (suara latar), foley (langkah kaki, kain), dan sound effect transisi (woosh, hit). Audio adalah 50% pengalaman video.`,
  've7': `Audio Mixing. Dialog harus paling jelas (sekitar -12db sampai -6db). Musik background jangan balapan dengan suara orang (gunakan teknik Ducking). Pastikan level audio seimbang.`,
  've8': `Transisi terbaik seringkali adalah 'Cut' biasa. Gunakan efek transisi (zoom, spin) hanya jika mendukung cerita, jangan berlebihan (norak). Invisible cut menyembunyikan potongan.`,
  've9': `Motion Graphics sederhana. Lower Thirds (nama pembicara), Title Intro, dan Call out text. Pahami Keyframe animation dasar (Position, Scale, Opacity) untuk membuat teks bergerak dinamis.`,
  've10': `Export Settings. Bitrate menentukan kualitas vs ukuran file. Codec H.264 (MP4) standar web. H.265 lebih efisien. Sesuaikan resolusi dan frame rate dengan platform tujuan (YouTube/IG/TikTok).`,

  // --- 3D Modeling Blender ---
  'bl1': `Navigasi 3D space (Orbit, Pan, Zoom) harus jadi memori otot. Hafalkan shortcut kunci (G-Grab, R-Rotate, S-Scale, E-Extrude). Interface Blender terlihat seram, tapi logis jika sudah biasa.`,
  'bl2': `Modeling Dasar. Mulai dari Primitive (Cube, Sphere). Edit Mode untuk manipulasi Vertex (titik), Edge (garis), dan Face (wajah). Usahakan Quads (segiempat), hindari N-gons untuk hasil shading bagus.`,
  'bl3': `Modifiers adalah magic. Subdivision Surface (menghaluskan), Mirror (simetri), Array (memperbanyak). Modifiers bersifat non-destruktif, bisa diubah kapan saja tanpa merusak model asli.`,
  'bl4': `Materials & Shading. Principled BSDF adalah shader serbaguna. Mainkan parameter: Base Color, Metallic (logam), Roughness (kilap/kusam), Transmission (kaca).`,
  'bl5': `Lighting membangun mood. Point light, Sun light, Area light. Three-Point Lighting (Key, Fill, Back) adalah teknik standar studio untuk menonjolkan objek 3D. HDRI memberikan pencahayaan lingkungan realistis instan.`,
  'bl6': `Rendering Engine: Eevee (Real-time, cepat seperti game engine) vs Cycles (Ray-tracing, fotorealistik tapi berat). Pahami Sampling dan Denoising untuk hasil bersih tanpa bintik (noise).`,
  'bl7': `UV Unwrapping seperti menguliti objek 3D menjadi lembaran 2D agar bisa dilukis tekstur. Seam placement (penempatan jahitan) penting agar tekstur tidak terlihat patah.`,
  'bl8': `Texturing menambahkan detail. Image Texture (foto kayu/batu) dihubungkan ke shader. Pahami peta lain: Normal Map (detail tonjolan palsu) dan Roughness Map (variasi kilap).`,
  'bl9': `Animasi dasar. Keyframe merekam posisi/rotasi/skala pada waktu tertentu. Graph Editor mengatur kurva kecepatan (Interpolation) agar gerakan tidak kaku (robotik) tapi luwes (ease-in/out).`,
  'bl10': `Compositing & Final Render. Menambahkan efek post-processing (Glow, Color Correction) langsung di Blender. Atur output resolution dan format file gambar/video.`,

  // --- Music Production ---
  'mp1': `DAW (Digital Audio Workstation) adalah studiomu. Ableton (bagus untuk elektronik/live), FL Studio (populer untuk beatmaking/hiphop), Logic (bagus untuk mac/recording). Pilih satu dan kuasai shortcut-nya.`,
  'mp2': `Rhythm adalah fondasi. Pelajari pola drum dasar genre favoritmu. Kick di ketukan 1, Snare di 2 & 4 (standar pop/rock). Gunakan Velocity (kekerasan pukulan) variatif agar drum terdengar manusiawi.`,
  'mp3': `Teori Musik Dasar membebaskanmu. Scale (tangga nada) menentukan nada yang 'benar'. Chord (kunci) membangun harmoni. Circle of Fifths membantu mencari chord yang cocok.`,
  'mp4': `Melodi adalah yang diingat orang. Melodi bagus biasanya punya pola 'Call and Response', repetisi, dan variasi ritmis. Gunakan telinga, kalau terdengar enak, berarti benar.`,
  'mp5': `Bassline jembatan ritme dan harmoni. Bass biasanya main di Root Note dari chord, tapi bisa jalan-jalan (walking bass) atau sinkopasi dengan Kick drum untuk Groove yang kuat.`,
  'mp6': `Arrangement (Struktur Lagu). Intro -> Verse -> Chorus -> Verse -> Chorus -> Bridge -> Chorus -> Outro. Kontras energi antar bagian penting agar lagu tidak membosankan (dinamika).`,
  'mp7': `Sound Selection > Mixing. Memilih suara kick dan bass yang sudah cocok dari awal jauh lebih mudah daripada mencoba memperbaikinya dengan EQ nanti. Kualitas sampel/preset sangat berpengaruh.`,
  'mp8': `EQ (Equalizer) membersihkan frekuensi. High Pass Filter buang frekuensi rendah keruh di instrumen non-bass. Beri ruang tiap instrumen di spektrum frekuensi agar tidak bertabrakan (muddy).`,
  'mp9': `Compression mengontrol dinamika (beda suara pelan dan keras). Membuat vokal konsisten rata, atau membuat drum lebih nendang (punchy). Reverb/Delay memberi dimensi ruang (depan/belakang).`,
  'mp10': `Finishing. Referencing (bandingkan dengan lagu pro). Cek di speaker laptop, HP, mobil. Export wav 44.1kHz/16bit atau 24bit. Jangan terjebak perfeksionisme, rilis adalah bagian dari belajar.`,

  // --- Podcasting ---
  'pod1': `Konsep & Niche. Podcast "ngobrolin apa aja" susah tumbuh. Spesifik lebih baik (misal: "Podcast Finansial untuk Gen Z"). Tentukan format: Solo (edukasi), Interview (tamu ahli), atau Storytelling (narasi).`,
  'pod2': `Kenali Listener Persona. Siapa mereka? Kapan mereka dengar? Masalah apa yang kamu bantu selesaikan atau hiburan apa yang mereka cari? Konten harus *user-centric*.`,
  'pod3': `Gear Audio. Mic USB dinamis (seperti Samson Q2U) lebih memaafkan ruangan bising dibanding kondensor. Ruangan penuh barang (lemari baju, sofa) lebih bagus akustiknya daripada ruangan kosong bergema.`,
  'pod4': `Teknik Mic. Jaga jarak sejengkal mulut. Gunakan Pop Filter untuk halau suara "P/B" (plosive). Mic technique yang baik mengurangi kerja editing 80%. Cek gain level jangan sampai clipping (merah).`,
  'pod5': `Skill Interview. Riset tamu sebelumnya. Jangan tanya pertanyaan standar yang ada di Google. Dengarkan jawaban tamu untuk follow-up question, jangan cuma fokus baca daftar pertanyaanmu.`,
  'pod6': `Editing Dasar. Potong bagian diam (dead air), "umm/ahh" yang berlebihan, dan kesalahan bicara. Tambahkan noise reduction jika perlu. Jaga alur percakapan tetap natural tapi padat.`,
  'pod7': `Sonic Branding. Musik Intro/Outro menciptakan identitas. Pastikan volume musik tidak menenggelamkan suara bicara (Ducking). Gunakan musik bebas royalti agar aman.`,
  'pod8': `Cover Art adalah 'wajah' di Spotify. Harus terbaca jelas di ukuran kecil (thumbnail HP). Gunakan wajah host (human connection) dan tipografi tebal kontras.`,
  'pod9': `Hosting & RSS. Spotify for Podcasters (gratis) adalah tempat upload file audio. Mereka akan generate RSS Feed untuk didistribusikan ke Apple Podcast, Google, dll secara otomatis.`,
  'pod10': `Promosi. Buat audiogram (video snippet) untuk IG Story/TikTok. Minta tamu share episode mereka. Konsistensi jadwal rilis (misal tiap Kamis) membangun kebiasaan pendengar.`,

  // --- Photography Basics ---
  'ph1': `Segitiga Eksposur: ISO (Sensitivitas sensor), Aperture (Bukaan lensa), Shutter Speed (Kecepatan rana). Ketiganya mengatur terang-gelap foto dan efek kreatifnya.`,
  'ph2': `Aperture (f-stop). Angka kecil (f/1.8) = bukaan besar = background blur (Bokeh) & terang. Angka besar (f/16) = bukaan kecil = semua tajam (Landscape) & gelap.`,
  'ph3': `Shutter Speed. Cepat (1/1000s) membekukan gerakan (olahraga). Lambat (1/10s) merekam jejak gerak (motion blur/light trails) tapi butuh tripod agar tidak goyang.`,
  'ph4': `ISO. Semakin tinggi ISO, semakin terang foto di tempat gelap, tapi muncul bintik-bintik (Noise/Grain). Selalu gunakan ISO terendah yang memungkinkan (ISO 100).`,
  'ph5': `Komposisi Rule of Thirds. Bagi layar jadi 9 kotak. Taruh subjek di titik pertemuan garis, bukan di tengah mati. Ini membuat foto lebih dinamis dan enak dilihat.`,
  'ph6': `Pencahayaan (Lighting). Golden Hour (pagi/sore) memberi cahaya lembut keemasan. Mid-day (siang bolong) memberi bayangan keras. Arah cahaya (depan, samping, belakang) mengubah mood.`,
  'ph7': `Fokus. Pastikan mata subjek (untuk potret) tajam. Pahami mode Auto Focus (AF-S untuk diam, AF-C untuk benda bergerak). Kunci fokus separuh tekan shutter.`,
  'ph8': `White Balance (WB). Mengatur suhu warna agar putih terlihat putih, tidak kekuningan atau kebiruan. Auto WB biasanya oke, tapi manual WB memberi kontrol kreatif.`,
  'ph9': `Editing bukan memalsukan, tapi menyempurnakan. Shoot format RAW (jika bisa) untuk data warna maksimal. Edit Exposure, Contrast, Highlight/Shadow di Lightroom/Snapseed.`,
  'ph10': `Storytelling. Foto bagus bercerita. Cari momen, emosi, atau perspektif unik. Jangan cuma memotret apa yang terlihat, potretlah apa yang *terasa*.`,

  // --- Effective Communication ---
  'ec1': `Active Listening bukan sekadar diam menunggu giliran bicara. Fokus penuh pada lawan bicara, validasi perasaan mereka, dan ulangi poin mereka (paraphrasing) untuk memastikan pemahaman.`,
  'ec2': `Bahasa Tubuh (Non-Verbal) bicara lebih keras dari kata-kata. Kontak mata, postur terbuka, dan anggukan menunjukkan ketertarikan. Senyum tulus membangun kepercayaan instan.`,
  'ec3': `Small Talk adalah pelumas sosial. Mulai dengan topik ringan (situasi sekitar, cuaca, hobi) untuk mencairkan suasana sebelum masuk topik berat. Teknik FORD: Family, Occupation, Recreation, Dreams.`,
  'ec4': `Kejelasan (Clarity). Hindari jargon rumit. Bicara to-the-point. Gunakan struktur: "Poin utama saya adalah X, alasannya Y, contohnya Z".`,
  'ec5': `Public Speaking. Grogi itu wajar. Ubah nervous jadi excitement. Persiapan matang adalah obatnya. Fokus memberi nilai pada audiens, bukan pada ketakutan diri sendiri.`,
  'ec6': `Storytelling. Fakta memberitahu, cerita menjual. Gunakan struktur narasi (Awal-Konflik-Resolusi) untuk menyampaikan pesan agar diingat dan menggugah emosi.`,
  'ec7': `Asertivitas. Berani berkata "Tidak" tanpa merasa bersalah, dan berani meminta apa yang kamu butuhkan dengan sopan tapi tegas. Hargai hak diri sendiri dan orang lain.`,
  'ec8': `Memberi Feedback. Gunakan metode Sandwich (Pujian - Kritik Konstruktif - Pujian) atau SBI (Situation-Behavior-Impact). Kritik perilakunya, bukan orangnya.`,
  'ec9': `Resolusi Konflik. Fokus pada masalah, bukan menyerang pribadi. Cari "Common Ground" (kepentingan bersama). Dengarkan sudut pandang lain sebelum membela diri.`,
  'ec10': `Persuasi & Negosiasi. Cari Win-Win Solution. Pahami apa motivasi dan kebutuhan orang lain, lalu bingkai argumenmu sebagai solusi bagi kebutuhan mereka.`,

  // --- Time Management ---
  'tf1': `Audit Waktu. Kamu merasa sibuk, tapi produktifkah? Lacak kemana waktumu pergi selama 3 hari. Kamu akan kaget berapa jam terbuang untuk scrolling sosmed atau rapat tidak penting.`,
  'tf2': `Pomodoro Technique. Otak fokus maksimal 25-50 menit. Kerja fokus 25 menit, istirahat 5 menit. Ini menjaga stamina mental seharian dan mencegah burnout.`,
  'tf3': `Eisenhower Matrix. Pisahkan tugas: Penting & Mendesak (Kerjakan Sekarang), Penting Tidak Mendesak (Jadwalkan - ini zona growth), Tidak Penting Mendesak (Delegasikan), Tidak Penting Tidak Mendesak (Hapus).`,
  'tf4': `Deep Work. Kemampuan kerja fokus tanpa distraksi pada tugas kognitif sulit. Matikan notifikasi, cari tempat tenang. 2 jam Deep Work > 8 jam kerja terdistraksi.`,
  'tf5': `Time Blocking & Calendar. Jangan pakai To-Do List panjang tanpa waktu. Beri "rumah" (slot waktu) di kalender untuk setiap tugas. Jika tidak ada di kalender, tidak akan dikerjakan.`,
  'tf6': `Manajemen Energi (Chronotype). Kenali kapan energi puncakmu (Pagi/Siang/Malam). Kerjakan tugas tersulit saat energi tinggi, tugas admin/rutin saat energi rendah.`,
  'tf7': `Digital Detox & Distraction. Notifikasi HP adalah musuh fokus. Gunakan mode 'Do Not Disturb'. Batasi cek email/chat hanya di jam tertentu (Batching).`,
  'tf8': `2-Minute Rule. Jika tugas butuh waktu kurang dari 2 menit (balas chat singkat, taruh sepatu), kerjakan SEKARANG. Menundanya memakan energi mental lebih besar untuk mengingatnya.`,
  'tf9': `Batching (Pengelompokan). Kelompokkan tugas sejenis. Balas semua email sekaligus dalam 30 menit, jangan satu-satu sepanjang hari. Switching cost (biaya ganti fokus) itu mahal.`,
  'tf10': `Review Mingguan. Hari Minggu/Jumat sore, evaluasi minggu lalu. Apa yang tercapai? Apa kendalanya? Rencanakan prioritas minggu depan agar Senin pagi langsung gas pol.`,

  // --- Emotional Intelligence ---
  'eq1': `Self-Awareness (Kesadaran Diri). Mampu mengenali emosi saat sedang terjadi. "Saya sedang marah". Menamai emosi (Labeling) mengurangi intensitasnya di otak.`,
  'eq2': `Identifikasi Triggers. Apa tombol merahmu? Kritik? Diabaikan? Menunggu? Mengetahui pemicu membantumu bersiap merespon dengan sadar, bukan bereaksi impulsif.`,
  'eq3': `Self-Regulation. Jeda antara Pemicu dan Respon. Tarik napas dalam, hitung sampai 10, atau pergi sebentar (Timeout). Jangan kirim email/chat saat emosi tinggi.`,
  'eq4': `Motivasi Internal. Orang dengan EQ tinggi didorong oleh tujuan pribadi, rasa ingin tahu, dan nilai diri, bukan sekadar uang atau pujian eksternal. Temukan "Why"-mu.`,
  'eq5': `Empati Kognitif. Memahami perspektif orang lain secara intelektual. "Saya mengerti kenapa dia berpikir begitu, meski saya tidak setuju".`,
  'eq6': `Empati Emosional. Merasakan apa yang orang lain rasakan. Menunjukkan kepedulian tulus. "Pasti berat ya mengalami itu". Ini membangun koneksi mendalam.`,
  'eq7': `Social Skills. Kemampuan navigasi situasi sosial, membangun rapport, dan jejaring. Baca suasana ruangan. Jadilah orang yang menyenangkan untuk diajak kerjasama.`,
  'eq8': `Mendengar Emosi. Perhatikan nada suara, ekspresi wajah, dan bahasa tubuh lawan bicara. Seringkali pesan sebenarnya ada di balik kata-kata.`,
  'eq9': `Manajemen Konflik EQ. Hadapi masalah dengan kepala dingin. Fokus mencari solusi, bukan mencari siapa yang salah. Gunakan pernyataan "Saya merasa..." daripada menuduh "Kamu selalu...".`,
  'eq10': `Membangun Hubungan. Investasi pada hubungan jangka panjang. Beri apresiasi tulus, ingat detail kecil tentang orang lain, dan bantu tanpa pamrih.`,

  // --- Home Maintenance ---
  'hm1': `Toolbox Wajib Punya: Palu kambing, Obeng set (plus/minus), Tang kombinasi, Kunci Inggris (Adjustable Wrench), Meteran, Waterpass, dan Tespen. Beli kualitas bagus, awet seumur hidup.`,
  'hm2': `Bor Listrik (Power Drill). Bedakan mata bor kayu, besi, dan beton (masonry). Gunakan fitur Hammer untuk tembok keras. Pasang Fischer agar sekrup di tembok kuat menahan beban.`,
  'hm3': `Plumbing Dasar. Keran bocor biasanya karena karet seal/washer aus. Matikan sumber air, buka kepala keran, ganti karet Rp 5.000. Gunakan Seal Tape putih pada drat agar rapat.`,
  'hm4': `Saluran Mampet. Jangan langsung bahan kimia keras. Coba plunger (kop) dulu. Bersihkan P-Trap (leher angsa) di bawah wastafel, biasanya kotoran menumpuk di sana.`,
  'hm5': `Mengecat Dinding. Persiapan 80%, Pengecatan 20%. Tutup lantai/mebel, lakban pinggiran (masking tape), tambal lubang, amplas, baru cat. Pola W atau M saat nge-roll agar rata.`,
  'hm6': `Listrik Dasar. Ganti saklar/stop kontak. ATURAN EMAS: Matikan MCB (listrik pusat) & cek pakai Tespen sebelum sentuh kabel. Hitam/Merah=Fasa (Setrum), Biru=Netral, Kuning=Ground.`,
  'hm7': `Tambal Dinding (Drywall/Semen). Lubang paku kecil cukup pakai pasta gigi/dempul (wall filler). Lubang besar butuh compound dan amplas setelah kering agar rata sebelum dicat.`,
  'hm8': `Merakit Furnitur (Knock-down). Baca manual DULU sampai habis. Kelompokkan baut/mur. Jangan kencangkan baut 100% sebelum semua terpasang pas, baru kencangkan akhir (biar presisi).`,
  'hm9': `Caulking (Lem Silikon). Mengganti silikon jamuran di pinggir wastafel/bathtub. Kerok silikon lama sampai bersih, bersihkan alkohol, aplikasikan silikon baru, ratakan dengan jari basah sabun.`,
  'hm10': `Emergency Shutoff. Wajib tahu lokasi Keran Utama Air (PAM) dan Panel Listrik (MCB) rumah. Labeli dengan jelas. Saat ada bocor besar atau korslet, lari ke sini dulu!`,

  // --- First Aid Basics ---
  'fa1': `Nomor Darurat & Mindset. Simpan 112 / 118 / 119 atau nomor RS terdekat. Prinsip DRSABC: Danger (Aman?), Response (Sadar?), Send help, Airway, Breathing, CPR. Jangan jadi korban kedua.`,
  'fa2': `CPR (RJP) Hands-only. Jika orang pingsan & tidak bernapas: Tekan tengah dada dengan tumit tangan, lengan lurus, tekan cepat & dalam (100-120x/menit, kedalaman 5cm). Lanjut sampai bantuan datang.`,
  'fa3': `Luka Pendarahan. Tekan langsung (Direct Pressure) pada sumber darah dengan kain bersih/kasa. Jangan buka-tutup untuk ngecek. Angkat bagian luka lebih tinggi dari jantung jika bisa.`,
  'fa4': `Luka Bakar. Dinginkan dengan AIR MENGALIR minimal 20 menit (bukan air es, bukan pasta gigi/mentega!). Tutup longgar dengan plastik wrap bersih agar tidak infeksi.`,
  'fa5': `Tersedak (Choking). Jika tidak bisa batuk/bicara, lakukan Heimlich Maneuver. Berdiri di belakang, peluk perut di atas pusar, hentakkan kepalan tangan ke dalam dan ke atas.`,
  'fa6': `Pingsan & Syok. Baringkan telentang. Angkat kaki lebih tinggi dari kepala (agar darah ke otak). Longgarkan pakaian ketat. Jaga suhu tubuh hangat. Jangan beri minum jika belum sadar penuh.`,
  'fa7': `Patah Tulang/Keseleo. Metode RICE: Rest (Istirahat), Ice (Kompres es 20 mnt), Compression (Balut tekan elastis), Elevation (Tinggikan). Jangan coba luruskan tulang bengkok! Pasang bidai (splint).`,
  'fa8': `Tas Siaga Bencana (Go-Bag). Siapkan tas dekat pintu berisi: Dokumen penting (plastik), P3K, Air minum, Makanan kaleng/bar, Senter, Baterai, Peluit, Uang tunai, Baju ganti.`,
  'fa9': `Kebakaran (Fire Safety). Cara pakai APAR: PASS (Pull pin, Aim base of fire, Squeeze handle, Sweep side-to-side). Jika api besar, tinggalkan. Tutup pintu untuk hambat api. Merayap jika ada asap.`,
  'fa10': `Mental Health First Aid. Serangan Panik: Temani, bicara tenang, ajak atur napas (4-7-8). Teknik Grounding 5-4-3-2-1 (Lihat 5 benda, Sentuh 4, Dengar 3, Cium 2, Rasa 1) untuk kembali ke realita.`,

  // --- Personal Branding ---
  'pb1': `Brand Audit. Googling namamu. Apa yang muncul? Itu brandmu saat ini. Hapus jejak digital negatif. Branding adalah apa yang orang katakan saat kamu tidak di ruangan.`,
  'pb2': `Value Proposition (UVP). Apa keunikanmu? Gabungan Skill + Pengalaman + Kepribadian. Rumus: "Saya membantu [Target] mencapai [Hasil] dengan [Cara Unik]".`,
  'pb3': `LinkedIn Optimization. Foto pro (senyum, lighting bagus). Banner visual. Headline bukan cuma jabatan, tapi value (misal: "Helping SaaS grow via SEO"). About section bercerita, bukan CV kaku.`,
  'pb4': `Content Strategy. Pilih 3 pilar topik (misal: Koding, Produktivitas, Karir). Konsisten sharing edukasi, opini, atau behind-the-scene. Konten membangun otoritas (Expertise).`,
  'pb5': `Networking Autentik. Jangan cuma add. Kirim pesan personal: "Hi, saya suka postmu tentang X". Beri nilai dulu (komen, share info) sebelum minta sesuatu. Networking = Bertani, bukan Berburu.`,
  'pb6': `Public Speaking Online. Buat video pendek atau webinar gratis. Kemampuan bicara di depan kamera meningkatkan persepsi profesionalisme dan kepercayaan secara drastis.`,
  'pb7': `Website Portofolio. Rumah digitalmu sendiri (bukan numpang di sosmed). Tampilkan: Siapa kamu, Apa jasamu, Bukti karya (Case Studies), Testimoni, dan Kontak. Pakai Carrd/Notion cukup.`,
  'pb8': `Social Proof. Minta rekomendasi LinkedIn dari bos/klien/rekan. Tampilkan logo klien atau sertifikat. Orang percaya apa kata orang lain tentangmu.`,
  'pb9': `Thought Leadership. Tulis artikel panjang (Medium/LinkedIn Article) tentang tren industri atau opini mendalam. Tunjukkan kamu punya wawasan, bukan cuma skill teknis.`,
  'pb10': `Konsistensi Sistem. Motivasi habis, sistem bertahan. Buat kalender konten. Luangkan 15 menit tiap pagi untuk engage di LinkedIn. Personal brand dibangun bata demi bata, bukan semalam.`,

  // --- Learning How to Learn ---
  'll1': `Mode Fokus vs Diffuse. Otak butuh fokus untuk input info, tapi butuh rileks (Diffuse) untuk menghubungkan ide (Aha moment). Stuck? Istirahat, jalan kaki, tidur. Biarkan otak bawah sadar kerja.`,
  'll2': `Active Recall. Membaca ulang itu pasif dan menipu (Illusion of Competence). Tes dirimu: Tutup buku, coba jelaskan kembali. Otak harus "berkeringat" menarik ingatan agar memori kuat.`,
  'll3': `Spaced Repetition. Kita lupa dengan cepat (Forgetting Curve). Review materi di interval waktu: 1 hari, 3 hari, 1 minggu, 1 bulan. Aplikasi Anki sangat membantu otomatisasi ini.`,
  'll4': `Feynman Technique. Cara terbaik belajar adalah mengajar. Coba jelaskan konsep rumit dengan bahasa sederhana seolah ke anak 5 tahun. Jika macet, berarti kamu belum paham di situ.`,
  'll5': `Interleaving. Jangan belajar blok (AAAA BBB CCCC). Campur materi (ABC BCA CAB). Ini melatih otak membedakan pola dan memilih strategi penyelesaian masalah yang tepat.`,
  'll6': `Manajemen Fokus (Pomodoro). Multitasking itu mitos. Otak butuh waktu untuk 'loading' konteks. Fokus tunggal 25 menit jauh lebih efektif daripada 2 jam terdistraksi notifikasi.`,
  'll7': `Mnemonic & Analogi. Otak suka gambar dan cerita. Buat singkatan lucu, lagu, atau "Istana Memori" (Memory Palace) untuk menghafal fakta kering. Hubungkan info baru dengan yang sudah kamu tahu.`,
  'll8': `Tidur & Belajar. Tidur bukan buang waktu. Saat tidur, otak membersihkan racun dan mengonsolidasi memori jangka pendek ke jangka panjang. Begadang belajar = lupa besoknya.`,
  'll9': `Prokrastinasi adalah masalah emosi (takut/bosan), bukan malas. Solusi: "Just Start" 5 menit. Rasa sakit psikologis biasanya hilang setelah kita mulai mengerjakan.`,
  'll10': `Deliberate Practice. Latihan buta tidak bikin jago. Latihan terarah: Fokus pada kelemahan spesifik, butuh konsentrasi tinggi, dan butuh feedback segera. Keluar dari zona nyaman.`,

  // --- Culinary Fundamentals ---
  'cf1': `Mise en Place (Everything in its place). Siapkan, cuci, potong, timbang semua bahan SEBELUM nyalakan kompor. Masak jadi tenang, tidak panik cari garam saat bawang sudah gosong.`,
  'cf2': `Knife Skills. Cara pegang pisau (pinch grip) dan tangan cakar (claw hand) agar jari aman. Potongan seragam = matang seragam. Kuasai dicing (dadu) dan julienne (korek api).`,
  'cf3': `Salt, Fat, Acid, Heat. 4 elemen rasa. Garam menonjolkan rasa. Lemak membawa rasa. Asam (jeruk/cuka) menyeimbangkan rasa berat. Panas menentukan tekstur. Masakan hambar? Kurang garam/asam.`,
  'cf4': `Pan Searing (Maillard Reaction). Reaksi kecokelatan pada daging/makanan di panas tinggi yang menciptakan rasa gurih kompleks. Kunci: Wajan panas, bahan kering (tidak basah), jangan diaduk terus.`,
  'cf5': `Braising (Ungkep/Stew). Teknik masak lambat api kecil dengan sedikit cairan untuk potongan daging murah/keras. Kolagen pecah jadi gelatin, daging jadi empuk dan saus jadi kental.`,
  'cf6': `Sauces. Saus mengubah bahan sederhana jadi mewah. Pelajari Béchamel (susu + roux) untuk pasta/lasagna, atau Vinaigrette (minyak + asam) untuk salad. Emulsi adalah kuncinya.`,
  'cf7': `Nasi & Pasta. Masak nasi: rasio air tepat, jangan buka tutup. Pasta: Air asin seperti laut, jangan pakai minyak, simpan air rebusan (pasta water) yang bertepung untuk mengentalkan saus.`,
  'cf8': `Sayuran. Jangan rebus sampai lembek abu-abu! Blanching (rebus cepat lalu celup air es) menjaga warna hijau cerah dan tekstur renyah. Roasting (panggang) mengeluarkan rasa manis alami.`,
  'cf9': `Plating. Kita makan dengan mata dulu. Beri dimensi tinggi, warna kontras, dan bersihkan pinggiran piring. Ganjil (3 atau 5 item) terlihat lebih natural daripada genap.`,
  'cf10': `Intuitive Cooking. Resep cuma panduan. Cicipi terus (Taste as you go). Belajar memperbaiki rasa: Terlalu manis? Tambah asam. Terlalu pedas? Tambah manis/lemak.`,

  // --- Drawing Sketching ---
  'dr1': `Kontrol Garis. Menggambar bukan dari pergelangan tangan, tapi dari bahu/siku untuk garis lurus panjang yang pede (ghosting). Latihan membuat garis lurus, lengkung C, dan S tanpa ragu.`,
  'dr2': `Bentuk Dasar (Primitives). Segala benda kompleks (mobil, manusia, pohon) bisa disederhanakan jadi Kotak, Bola, dan Silinder. Belajar melihat dunia dalam bentuk 3D ini.`,
  'dr3': `Perspektif 1 Titik Hilang. Benda makin jauh makin kecil menuju satu titik. Cocok untuk gambar jalan, rel kereta, atau interior ruangan dari depan.`,
  'dr4': `Perspektif 2 Titik Hilang. Melihat objek dari sudut (corner). Garis horizontal lari ke titik hilang kiri dan kanan. Ini cara kita melihat gedung/kotak sehari-hari.`,
  'dr5': `Pencahayaan & Shading. Cahaya menciptakan bayangan yang memberi ilusi 3D (Form). Pahami Highlight, Midtone, Core Shadow, Reflected Light, dan Cast Shadow pada bola.`,
  'dr6': `Proporsi & Pengukuran. Gunakan pensil sebagai alat ukur. Bandingkan tinggi vs lebar. "Kepala ini berapa kali tinggi badan?". Proporsi salah membuat gambar terlihat aneh (uncanny).`,
  'dr7': `Komposisi. Jangan selalu taruh objek di tengah. Gunakan Rule of Thirds, Leading Lines, atau Framing untuk memandu mata penonton ke titik fokus gambar.`,
  'dr8': `Tekstur. Jangan gambar setiap helai rambut/rumput. Gambar impresi teksturnya lewat pola goresan. Kayu kasar vs Logam licin punya cara arsir beda.`,
  'dr9': `Wajah Manusia (Loomis Method). Kepala bukan bola bulat, tapi bola dengan sisi datar. Mata ada di tengah ketinggian kepala (bukan di atas!). Telinga sejajar alis dan hidung.`,
  'dr10': `Still Life (Alam Benda). Latihan terbaik observasi. Susun buah/botol, beri lampu. Gambar apa yang kamu LIHAT, bukan apa yang kamu PIKIRKAN (misal: bibir gelas itu elips, bukan lonjong runcing).`,

  // --- Meditation Mindfulness ---
  'med1': `Fokus Napas (Anapanasati). Objek meditasi paling dasar. Perhatikan sensasi udara masuk/keluar di hidung atau kembang kempis perut. Saat pikiran melayang, sadari, lalu *lembut* kembali ke napas.`,
  'med2': `Body Scan. Relaksasi progresif. Pindahkan fokus dari ujung kaki sampai kepala. Rasakan ketegangan otot dan lepaskan. Ini sangat efektif untuk tidur atau meredakan stres fisik.`,
  'med3': `Noting (Melabeli). Saat terdistraksi, beri label netral: "Berpikir", "Mendengar", "Merasakan". Ini menciptakan jarak antara kamu dan pikiranmu (Meta-awareness). Kamu bukan pikiranmu.`,
  'med4': `Walking Meditation. Meditasi tidak harus duduk diam. Saat jalan, sadari sensasi telapak kaki menyentuh tanah, angin di kulit, bunyi sekitar. Bawa kesadaran ke aktivitas fisik.`,
  'med5': `Loving Kindness (Metta). Melatih rasa welas asih. Ucapkan doa baik untuk diri sendiri, orang tercinta, orang netral, hingga orang yang sulit. "Semoga kamu bahagia, semoga kamu bebas derita".`,
  'med6': `Mindful Eating. Matikan TV/HP. Lihat warna makanan, cium aromanya, kunyah perlahan, rasakan tekstur dan rasanya berubah. Makan jadi pengalaman kaya, bukan sekadar isi bensin.`,
  'med7': `Teknik Grounding 5 Indra. Saat cemas/panik, kembali ke saat ini (Here & Now). Sebutkan 5 hal yang dilihat, 4 diraba, 3 didengar, 2 dicium, 1 dirasa.`,
  'med8': `Visualisasi. Otak tidak bisa membedakan imajinasi kuat dan realita. Visualisasikan tempat aman (pantai/gunung) atau visualisasikan dirimu berhasil melakukan tugas sulit dengan tenang.`,
  'med9': `Mindfulness Sehari-hari. Pilih satu kegiatan rutin (sikat gigi, cuci piring, minum kopi) untuk dilakukan dengan sadar penuh (presence). Jangan multitasking di momen ini.`,
  'med10': `Silent Retreat Mini. Cobalah diam total tanpa bicara, tanpa gadget, tanpa baca selama 1 jam atau setengah hari. Amati betapa bisingnya pikiranmu saat stimulus luar dihentikan.`,

  // --- Urban Gardening ---
  'gr1': `Sun Mapping. Tanaman butuh makan cahaya. Sayuran buah (tomat/cabe) butuh 6-8 jam matahari langsung (Full Sun). Sayuran daun (sawi/selada) bisa di tempat teduh parsial (3-4 jam).`,
  'gr2': `Media Tanam. Tanah taman biasa di pot akan memadat dan mencekik akar. Buat campuran gembur: 1 Tanah : 1 Kompos/Pupuk Kandang : 1 Sekam Bakar/Cocopeat. Harus poros (air cepat turun).`,
  'gr3': `Benih & Semai. Benih kecil (sawi) tabur tipis di permukaan. Benih besar (kacang) tanam sedalam 2x ukuran benih. Jaga kelembapan (spray halus) jangan sampai kering atau becek. Tutup gelap sampai pecah kecambah (sprout).`,
  'gr4': `Penyiraman. Kesalahan pemula: Overwatering (akar busuk). Cek tanah dengan jari sedalam 2cm. Jika kering, siram sampai air keluar dari lubang bawah pot. Siram pagi hari terbaik.`,
  'gr5': `Wadah/Pot. Pastikan ada lubang drainase! Tanpa lubang = kolam = akar busuk. Botol bekas, kaleng, karung beras bisa jadi pot asalkan dilubangi bawahnya.`,
  'gr6': `Pemupukan (Nutrisi). Tanaman di pot butuh suplai makanan. N (Nitrogen) untuk daun hijau. P (Fosfor) untuk akar/bunga. K (Kalium) untuk buah/kekebalan. Kompos/POC (Pupuk Organik Cair) rutin seminggu sekali.`,
  'gr7': `Hama & Penyakit. Kutu putih, ulat, jamur. Semprot pestisida nabati (campuran air sabun cuci piring + minyak + bawang putih) sebagai pencegahan. Ambil manual ulat yang terlihat.`,
  'gr8': `Pruning (Pemangkasan). Pucuk dipotong (topping) merangsang cabang samping tumbuh rimbun (bushy). Buang daun kuning/tua di bawah agar sirkulasi udara lancar dan fokus nutrisi ke pucuk muda.`,
  'gr9': `Regrow Sisa Dapur. Jangan buang bonggol daun bawang, seledri, kangkung, atau sawi. Tancapkan lagi ke tanah atau air, mereka akan tumbuh kembali. Cara termudah mulai berkebun.`,
  'gr10': `Panen & Rotasi. Sayuran daun bisa panen 'cut and come again' (potong daun tua, sisa tanaman tumbuh lagi). Setelah panen, gemburkan tanah dan tambah kompos lagi sebelum tanam baru.`,

  // --- Yoga Flexibility ---
  'yg1': `Pranayama (Napas). Yoga adalah penyatuan napas dan gerak. Ujjayi breath (napas laut) lewat hidung menghangatkan tubuh. Jangan tahan napas saat pose sulit, itu bikin tegang dan pusing.`,
  'yg2': `Surya Namaskar (Sun Salutation). Rangkaian 12 gerakan mengalir (Flow) untuk pemanasan seluruh tubuh. Sinkronisasi: Tarik napas (angkat tangan), Buang napas (bungkuk). Ulangi 3-5 kali.`,
  'yg3': `Warrior Poses (Virabhadrasana). Melatih kekuatan kaki, pinggul, dan fokus mental. Warrior II: Kaki depan tekuk 90 derajat, tangan rentang, mata tajam ke depan. Kaki belakang lurus kuat.`,
  'yg4': `Balance (Vrikshasana/Tree Pose). Keseimbangan fisik melatih fokus pikiran. Tumpu satu kaki, kaki lain di betis/paha (JANGAN di lutut!). Fokus mata pada satu titik diam (Drishti).`,
  'yg5': `Forward Folds (Uttanasana). Meregangkan seluruh rantai otot belakang (punggung & hamstring). Tidak harus sentuh jari kaki! Tekuk lutut agar perut nempel paha lebih aman buat punggung bawah.`,
  'yg6': `Backbends (Cobra/Bridge). Melawan postur bungkuk akibat duduk/HP. Buka dada dan bahu. Aktifkan otot pantat dan punggung, jangan tumpu beban di pinggang bawah (low back crunch).`,
  'yg7': `Twists (Puntiran). Memeras organ perut (detoks) dan memobilisasi tulang belakang. Lakukan saat buang napas untuk puntiran lebih dalam. Jaga punggung tetap tegak lurus.`,
  'yg8': `Hip Openers (Pigeon Pose). Pinggul menyimpan banyak stres emosi. Pose ini intens tapi melegakan. Jaga pinggul sejajar (square). Bernapas ke bagian yang terasa kencang.`,
  'yg9': `Inversions (Downward Dog). Kepala di bawah jantung. Mengalirkan darah ke otak, menenangkan sistem saraf. Tekan kuat telapak tangan, dorong pantat ke langit, tumit arahkan ke lantai.`,
  'yg10': `Savasana (Corpse Pose). Pose tersulit: Diam total. Izinkan tubuh menyerap manfaat latihan. Rilekskan rahang, lidah, bahu. Bukan tidur, tapi sadar dalam relaksasi (Resting Awareness).`,

  // --- Interior Design ---
  'id1': `Fungsi Sebelum Estetika. Ruangan cantik tapi ribet itu gagal. Analisis: Siapa yang pakai? Untuk apa? Apa aktivitas utamanya? Desain harus mendukung aktivitas tersebut.`,
  'id2': `Gaya Desain. Temukan style-mu. Minimalis (Clean, less is more), Industrial (Raw, besi/beton ekspos), Scandinavian (Kayu terang, cozy, fungsional), Bohemian (Ramai, tekstur, tanaman). Konsisten pada satu gaya utama.`,
  'id3': `Skema Warna 60-30-10. Rumus anti gagal: 60% Warna Dominan (Dinding/Lantai - Netral), 30% Warna Sekunder (Furniture utama), 10% Warna Aksen (Bantal/Dekorasi - Cerah/Kontras).`,
  'id4': `Lighting Layers. Jangan cuma satu lampu plafon (datar & membosankan). Gunakan 3 lapis: Ambient (Cahaya umum), Task (Lampu baca/kerja), Accent (Lampu sorot lukisan/tanaman untuk mood). Warna lampu (Warm vs Cool) juga krusial.`,
  'id5': `Layout & Flow. Sirkulasi (jalan orang) jangan terhalang. Beri jarak antar furnitur. Jangan tempel semua furnitur ke tembok (efek ruang tunggu). Buat area percakapan yang intim.`,
  'id6': `Decluttering. Barang menumpuk bikin stres visual. Buang/donasikan yang tak perlu. "A place for everything, and everything in its place". Storage tertutup (lemari) bikin ruang terlihat rapi.`,
  'id7': `Tekstur & Tekstil. Ruangan terasa dingin? Tambahkan tekstur: Karpet bulu, bantal rajut, selimut katun, meja kayu kasar. Tekstur memberi kehangatan dan dimensi tanpa menambah warna.`,
  'id8': `Dekorasi Dinding & Focal Point. Tiap ruangan butuh satu titik fokus (TV, Lukisan Besar, Jendela). Gantung lukisan setinggi mata (center 145-150cm dari lantai), jangan terlalu tinggi.`,
  'id9': `Tanaman Indoor. Elemen hidup bikin ruangan segar instant. Pilih tanaman sesuai cahaya: Lidah Mertua/Sirih Gading (tahan banting minim cahaya), Monstera/Karet Kebo (cahaya terang).`,
  'id10': `Moodboard. Sebelum beli barang, kumpulkan gambar inspirasi, palet warna, dan foto furnitur dalam satu kolase. Lihat apakah mereka cocok bersanding. Ini mencegah salah beli yang mahal.`,

  // --- Barista Skills ---
  'bs1': `Biji Kopi. Arabica (asam buah, wangi, mahal) vs Robusta (pahit, bold, kafein tinggi). Fresh Roast (baru sangrai < 1 bulan) adalah kunci rasa enak. Kopi supermarket biasanya sudah apek (stale).`,
  'bs2': `Grind Size (Gilingan). Ini variabel terpenting. Halus (seperti tepung) untuk Espresso. Sedang (pasir/garam) untuk V60. Kasar (garam laut) untuk French Press. Salah giling = salah ekstraksi.`,
  'bs3': `Air. Kopi adalah 98% air. Gunakan air mineral atau filter, jangan air keran (kaporit merusak rasa). Suhu ideal 90-96°C. Jangan air mendidih (gosong/pahit) atau terlalu dingin (asam/hambar).`,
  'bs4': `French Press (Immersion). Cara termudah. Kopi kasar + air panas, diamkan 4 menit, tekan. Hasilnya bold, body tebal, berminyak. Cocok untuk kopi tubruk naik kelas.`,
  'bs5': `Pour Over (V60). Teknik tuang melingkar. Butuh ketel leher angsa. Hasilnya bersih (clean), body ringan, menonjolkan rasa buah/bunga. Filter kertas menyaring minyak.`,
  'bs6': `Teori Ekstraksi. Kopi adalah kimia. Under-extracted (kurang seduh) = Asam kecut, asin, tipis. Over-extracted (kelamaan) = Pahit, sepat, kering. Ideal = Manis, seimbang (Sweet Spot).`,
  'bs7': `Blooming. Tuang sedikit air di awal (2-3x berat kopi) dan tunggu 30 detik. Ini membuang gas CO2 (degassing) agar air bisa mengekstraksi rasa kopi dengan maksimal.`,
  'bs8': `Cold Brew. Kopi kasar + air suhu ruang, simpan kulkas 12-24 jam. Ekstraksi lambat menghasilkan kopi rendah asam, manis alami, dan smooth. Tahan lama di kulkas.`,
  'bs9': `Maintenance. Minyak kopi itu jahat, lama-lama jadi tengik. Bersihkan alat seduh segera. Descaling mesin/ketel berkala dari kerak kapur air. Grinder bersih = rasa bersih.`,
  'bs10': `Rasio Seduh (Brew Ratio). Standar 1:15 (1 gram kopi : 15 ml air) sampai 1:18. Mau lebih kuat? Pakai 1:12. Mau lebih ringan? 1:18. Gunakan timbangan digital agar konsisten tiap hari.`,

  // --- Critical Thinking ---
  'ct1': `Fakta vs Opini. Fakta bisa dibuktikan (objektif). Opini adalah perasaan/pandangan (subjektif). Berita sering mencampur keduanya. "Jakarta macet" (Fakta data) vs "Jakarta kota terburuk" (Opini).`,
  'ct2': `Cognitive Biases. Otak kita malas dan suka jalan pintas. Confirmation Bias (cari info yang dukung keyakinan sendiri), Sunk Cost Fallacy (lanjut karena sudah terlanjur basah), Halo Effect (orang cakep dianggap pintar). Sadari biasmu.`,
  'ct3': `Logical Fallacies. Kesesatan logika argumen. Ad Hominem (serang orangnya, bukan argumennya), Strawman (memelintir argumen lawan agar mudah diserang), False Dilemma (seolah cuma ada 2 pilihan).`,
  'ct4': `Socratic Questioning. Bertanya untuk menggali kebenaran, bukan untuk menang debat. "Apa buktinya?", "Apakah ada alternatif lain?", "Apa implikasinya?". Kupas lapisan asumsi sampai inti.`,
  'ct5': `First Principles Thinking. Cara berpikir Elon Musk. Jangan membeo (analogi). Bongkar masalah sampai ke kebenaran fundamental yang tidak bisa dibantah lagi, lalu bangun solusi dari sana.`,
  'ct6': `Literasi Data. Jangan mudah ditipu grafik. Cek sumbu Y (apakah mulai dari nol?), skala logaritmik, atau korelasi vs kausalitas (Es krim naik, hiu naik -> bukan sebab akibat, tapi karena musim panas).`,
  'ct7': `Steelmanning. Kebalikan Strawman. Coba bangun argumen lawan sekuat mungkin, pahami posisi terbaik mereka, BARU bantah. Ini membuat argumenmu jauh lebih kredibel dan empatik.`,
  'ct8': `Occam's Razor. Jika ada 2 penjelasan, yang lebih sederhana (minim asumsi) biasanya yang benar. Jangan cari konspirasi rumit jika kebodohan/kebetulan bisa menjelaskannya.`,
  'ct9': `Root Cause Analysis (Fishbone/5 Whys). Jangan obati gejala. Tanya "Kenapa?" 5 kali berturut-turut sampai ketemu akar masalah sesungguhnya.`,
  'ct10': `Decision Matrix. Buat keputusan objektif. List opsi di baris, kriteria di kolom (misal: Harga, Kualitas, Usaha). Beri bobot nilai. Hitung skor total. Matematika membantu emosi memilih.`,

  // --- Problem Solving ---
  'ps1': `Definisikan Masalah. Masalah yang didefinisikan dengan baik adalah setengah terselesaikan. Jangan bilang "Penjualan turun". Bilang "Penjualan produk X turun 20% di Q3 pada segmen remaja".`,
  'ps2': `5 Whys. Teknik Toyota. Tanya "Kenapa" berulang kali untuk menembus gejala permukaan menuju akar penyebab teknis atau sistemik.`,
  'ps3': `First Principles (Lagi). Dekonstruksi masalah kompleks menjadi bagian-bagian dasar yang sudah pasti benar. Lalu rakit ulang solusi dari nol tanpa terbebani "cara lama".`,
  'ps4': `Brainstorming (Divergent Thinking). Kuantitas > Kualitas di tahap ini. Tunda kritik. Ide gila diterima. Tujuannya mengumpulkan opsi sebanyak mungkin.`,
  'ps5': `Pareto Principle (80/20). 80% masalah disebabkan 20% penyebab. Fokuslah menyelesaikan 20% penyebab vital itu untuk dampak maksimal dengan usaha minimal.`,
  'ps6': `Decision Matrix (Convergent Thinking). Saatnya memilih. Gunakan tabel bobot untuk menilai ide-ide brainstorming secara logis dan objektif.`,
  'ps7': `Risk Assessment (Pre-mortem). Bayangkan solusi ini GAGAL di masa depan. Kenapa bisa gagal? Identifikasi risiko di awal dan buat rencana mitigasi sekarang.`,
  'ps8': `OODA Loop. Observe (Amati), Orient (Posisikan), Decide (Putuskan), Act (Bertindak). Siklus cepat yang dipakai pilot tempur untuk beradaptasi dengan situasi yang berubah cepat.`,
  'ps9': `Design Thinking. Empathize (Pahami user), Define, Ideate, Prototype, Test. Solusi harus Desirable (User mau), Viable (Bisnis untung), dan Feasible (Teknis bisa).`,
  'ps10': `Mental Models. Gunakan 'Inversion' (Bagaimana cara menyebabkan masalah ini? Lalu hindari itu). Gunakan 'Second Order Thinking' (Apa dampak dari dampaknya?).`,

  // --- Language Learning ---
  'llg1': `Immersion (Pencelupan). Ganti bahasa HP, tonton YouTube, dengar lagu dalam bahasa target. Otak butuh paparan konstan untuk menganggap bahasa itu "penting" untuk bertahan hidup.`,
  'llg2': `Pareto Principle Kata. Hafal 1000 kata paling umum mencakup 85% percakapan sehari-hari. Jangan hafal nama buah langka dulu. Fokus kata kerja, kata ganti, dan kata sambung frekuensi tinggi.`,
  'llg3': `Pronunciation & Shadowing. Tiru bunyi native speaker seperti burung beo. Rekam suaramu, bandingkan. Latih otot mulut untuk bunyi asing. Aksen bagus menutupi grammar pas-pasan.`,
  'llg4': `Sentence Mining. Jangan hafal kata lepas. Hafal Frasa atau Kalimat Utuh (Context). Otak mengingat cerita/situasi lebih baik daripada kamus.`,
  'llg5': `Grammar Dasar. Pahami struktur kalimat (SPO). Jangan terjebak aturan rumit di awal. Cukup tahu cara menyusun kalimat positif, negatif, dan tanya masa kini/lampau/depan.`,
  'llg6': `Input Hypothesis (Krashen). Belajar lewat input yang dimengerti (Comprehensible Input). Baca buku anak atau nonton kartun. Jika kamu paham 70-80%, kamu sedang belajar cepat.`,
  'llg7': `Language Exchange. Cari partner native yang mau belajar bahasamu. Aplikasi HelloTalk/Tandem. Barter waktu: 15 menit bahasa dia, 15 menit bahasa kamu.`,
  'llg8': `Berpikir dalam Bahasa Target. Stop menerjemahkan di kepala (Indo -> Inggris -> Mulut). Lihat meja, langsung pikir "Table". Narasi kegiatanmu dalam hati pakai bahasa baru.`,
  'llg9': `Spaced Repetition (Anki). Gunakan flashcard digital untuk review kosakata tepat sebelum kamu lupa. Ini cara tercepat menanamkan memori jangka panjang (SRS).`,
  'llg10': `Fearless Speaking. Berani salah! Kesalahan adalah data untuk perbaikan. Native speaker menghargai usahamu. Bicara patah-patah lebih baik daripada diam sempurna.`,

  // --- Research Skills ---
  'rs1': `Google Fu (Search Operators). Gunakan tanda kutip "..." untuk frase persis. site:ac.id untuk cari di web kampus. filetype:pdf untuk cari dokumen. minus (-) untuk mengecualikan kata.`,
  'rs2': `CRAAP Test. Evaluasi sumber: Currency (Baru?), Relevance (Sesuai?), Authority (Siapa penulisnya?), Accuracy (Ada bukti?), Purpose (Fakta atau jualan/propaganda?).`,
  'rs3': `Academic Databases. Google Scholar, DOAJ, ResearchGate. Di sini tempat ilmu terverifikasi (Peer-reviewed), bukan blog sembarangan.`,
  'rs4': `Membaca Jurnal Cepat. Jangan baca urut! Baca Judul -> Abstrak -> Kesimpulan -> Grafik/Tabel. Jika relevan, baru baca Metodologi dan Pembahasan. Hemat waktu.`,
  'rs5': `Zettelkasten / Note Taking. Jangan cuma copy-paste. Tulis ulang dengan bahasamu sendiri (Paraphrase). Hubungkan ide baru dengan ide lama yang sudah kamu tahu.`,
  'rs6': `Synthesis. Penelitian bukan kliping pendapat orang. Cari benang merah, pertentangan, atau pola dari berbagai sumber. Gabungkan menjadi pemahaman baru yang utuh.`,
  'rs7': `Sitasi & Plagiarisme. Hormati karya orang. Catat sumber saat mencatat ide. Gunakan tool sitasi (Mendeley/Zotero) untuk otomatisasi daftar pustaka APA/MLA.`,
  'rs8': `Primary Research. Jika data tidak ada di Google, cari sendiri. Buat survei (Google Form) atau wawancara narasumber. Data primer bernilai tinggi karena unik.`,

  // --- Stoicism Mindset ---
  'sto1': `Dichotomy of Control. Ada hal dalam kendali kita (pikiran, tindakan) dan di luar kendali (cuaca, opini orang, masa lalu). Fokus 100% pada yang bisa dikontrol, ikhlas pada yang tidak.`,
  'sto2': `Negative Visualization (Premeditatio Malorum). Bayangkan skenario terburuk sesekali. "Apa kalau aku dipecat?". Ini mengurangi rasa takut dan membuatmu lebih bersyukur atas apa yang ada sekarang.`,
  'sto3': `Journaling. Refleksi diri adalah ritual Stoic. Pagi: Set intensi. Malam: Review tindakan. "Apa yang sudah kulakukan dengan baik? Apa yang bisa diperbaiki?".`,
  'sto4': `Voluntary Discomfort. Latih ketahanan mental dengan sengaja susah. Mandi air dingin, puasa, tidur di lantai. Ini membuktikan "aku bisa bertahan walau tidak nyaman".`,
  'sto5': `Memento Mori. Ingat kamu akan mati. Ini bukan depresi, tapi motivasi. Waktu terbatas, jangan sia-siakan untuk hal remeh atau dendam. Hiduplah bermakna hari ini.`,
  'sto6': `Amor Fati. Cintai takdir. Jangan cuma terima nasib, tapi cintai apa pun yang terjadi. "Macet? Bagus, waktu buat denger podcast". Ubah hambatan jadi jalan.`,
  'sto7': `The View from Above. Zoom out. Masalahmu terlihat besar sekarang, tapi dari sudut pandang semesta/sejarah, itu kecil sekali. Ini memberi perspektif dan ketenangan.`,
  'sto8': `Sympatheia. Kita semua bagian dari satu organisme besar (kemanusiaan). Berbuat baik pada orang lain itu alami, seperti tangan kiri membantu tangan kanan.`,

  // --- Bodyweight Fitness ---
  'bwf1': `Mobilitas Sendi. Calisthenics butuh sendi kuat, terutama pergelangan tangan dan bahu. Pemanasan dinamis wajib hukumnya untuk mencegah cedera jangka panjang.`,
  'bwf2': `Perfect Push-up. Badan lurus seperti papan (plank), pantat jangan nungging/turun. Dada sentuh lantai, kunci siku saat naik (full range of motion). Kualitas > Kuantitas.`,
  'bwf3': `Hollow Body Hold. Fondasi kekuatan inti (core). Punggung bawah menempel lantai, kaki dan bahu angkat sedikit. Posisi "pisang" ini kunci kestabilan semua gerakan gimnastik.`,
  'bwf4': `Bodyweight Rows (Australian Pull-up). Melatih punggung dan bisep. Tarik dada ke bar rendah/meja. Kunci bahu ke belakang (retraksi skapula). Persiapan menuju Pull-up.`,
  'bwf5': `Dips. Melatih dada, tricep, bahu depan. Turun sampai siku 90 derajat, naik sampai lurus. Jangan angkat bahu ke telinga. Condong depan = dada, tegak = tricep.`,
  'bwf6': `Negative Pull-up. Belum kuat naik? Lompat ke atas bar, lalu TAHAN saat turun selambat mungkin. Ini melatih kekuatan eksentrik otot untuk membangun kekuatan tarik.`,
  'bwf7': `The Pull-up. Raja latihan tubuh atas. Mulai dari gantung lurus (dead hang), tarik sampai dagu lewat bar, turun terkontrol. Jangan mengayun (kipping) kalau mau otot jadi.`,
  'bwf8': `Squats. Kaki adalah fondasi. Jongkok sampai paha paralel lantai, punggung lurus, tumit tetap di lantai. Lutut boleh lewat jari kaki asalkan tumit tidak jinjit.`,
  'bwf9': `HIIT / AMRAP. Kardio tanpa lari. "As Many Rounds As Possible" dalam 15 menit. Kombinasi Burpees, Jumping Jacks, Squats tanpa istirahat panjang. Membakar lemak efektif.`,
  'bwf10': `L-Sit. Latihan core tingkat lanjut. Tumpu tangan di lantai/parallettes, angkat badan dan luruskan kaki ke depan membentuk huruf L. Butuh tricep, core, dan fleksibilitas paha belakang.`
};
